### ISSUE TITLE
Remove file restriction - We need to authorize JavaScript file type to craete Web file correctly.

### ISSUE THREAD

**Issue by bnepal** [MscrmTools/MscrmTools.PortalRecordsMover#43]
Having a issue with Remove File restriction step while moving portal records, could you please let me know how to tackle this error, is there any setting I need to enable / changed.
log below
Thanks

*************************
2020-11-02 03:30:09.152 PM		Info	Deactivating Webpage plugins steps
2020-11-02 03:30:11.393 PM		Info	Webpage plugins steps deactivated
2020-11-02 03:30:11.403 PM		Info	Removing JavaScript file restriction
2020-11-02 03:30:11.952 PM		Error	System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Object reference not set to an instance of an object. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040265
Message: Object reference not set to an instance of an object.
TimeStamp: 2020-11-02T04:30:12.1127484Z
OriginalException: Microsoft.Xrm.Sdk.InvalidPluginExecutionException
   at EDG.CRMPlugins.Annotation.PreOperationannotationCreate_AuditChanges.ExecuteCrmPlugin(LocalPluginContext localContext)
   at EDG.CRMPlugins.Annotation.PluginBase.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.<>c__DisplayClass17_0.<Execute>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain, String crashOnPluginExceptionM...).

***************

**Comment by bnepal** [comment]
looks like a custom plugin issue
