### ISSUE TITLE
Export failed with Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mahipalreddybhusireddy** [MscrmTools/MscrmTools.PortalRecordsMover#52]
We are triggering through DevOps task and below is error message. Is we are missing any input arguments? 
and issue getting suddenly ..Help please.. 

2021-12-02T12:13:44.4658169Z 2021-12-02 12.13.44: Initializing the Settings
2021-12-02T12:13:44.4665199Z 2021-12-02 12.13.44: command line arg: Name: settings, Value: ExtractWebRolesOnly.json
2021-12-02T12:13:44.4666152Z 2021-12-02 12.13.44: command line arg: Name: exportfile, Value: WebRoles.xml
2021-12-02T12:13:44.4666742Z 2021-12-02 12.13.44: command line arg: Name: user, Value: <myuser>
2021-12-02T12:13:44.6681629Z 2021-12-02 12.13.44: ActiveItemsOnly: True
2021-12-02T12:13:44.6682317Z CreateFilter: 
2021-12-02T12:13:44.6682751Z ModifyFilter: 
2021-12-02T12:13:44.6683130Z DateFilterOptions: CreateAndModify
2021-12-02T12:13:44.6683563Z BatchCount: 10
2021-12-02T12:13:44.6683958Z WebsiteFilter: 00000000-0000-0000-0000-000000000000
2021-12-02T12:13:44.6684364Z ImportFilename: 
2021-12-02T12:13:44.6684726Z ExportFilename: WebRoles.xml
2021-12-02T12:13:44.6685112Z PriorDaysToRetrieve: 
2021-12-02T12:13:44.6685615Z Username: <myuser>
2021-12-02T12:13:44.6686003Z Password: ********
2021-12-02T12:13:44.6686413Z SourceEnvironment: https://sssss.crm6.dynamics.com/
2021-12-02T12:13:44.6686849Z TargetEnvironment: 
2021-12-02T12:13:44.6687328Z SelectedEntities:
2021-12-02T12:13:44.6687688Z adx_website, adx_webrole
2021-12-02T12:13:44.6687931Z 
2021-12-02T12:13:44.6688444Z 2021-12-02 12.13.44: Beginning the export - SourceEnvironment: https://ssssss.crm6.dynamics.com/, ExportFilename:WebRoles.xml
2021-12-02T12:13:49.9268536Z 2021-12-02 12.13.49: Loading Metadata for current environment: https://ssssss.crm6.dynamics.com/
2021-12-02T12:13:49.9513338Z 
2021-12-02T12:13:49.9525553Z Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
2021-12-02T12:13:49.9526441Z    at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Execute(OrganizationRequest request)
2021-12-02T12:13:49.9527178Z    at PortalRecordsMover.AppCode.MetadataManager.GetEntitiesList(IOrganizationService service, List`1 logicalNames)

**Comment by MscrmTools** [comment]
Hi @mahipalreddybhusireddy, sorry I missed this issue.
But if used in DevOps, then it's not my tool but the fork made by @jamesnovak 
So I will close the issue. You can open an issue on the [appropriate repository](https://github.com/jamesnovak/PortalRecordsMoverConsole)
